#!/usr/bin/env python3
"""Port the crew sidebar's pixel cat into board.html.

    python3 cat_from_swift.py [--check]

The cat is NOT redrawn here. Its six poses are read straight out of
~/.config/cmux/sidebars/crew.swift -- the same [[x, y, colour], ...] arrays the
SwiftUI sidebar renders as Rectangles -- so the HTML board and the sidebar show
the same animal, pixel for pixel, and a change to one can be replayed into the
other. Hand-transcribing 700 pixels was never an option.

Each pose becomes one <path> per colour, with every pixel as a 3x3 square, which
turns ~120 rects into ~5 paths and keeps board.html readable. The output is a
single <svg id="cat"> block written between two markers in board.html; the
animation lives in CSS, because the page is inert and pushes are two minutes
apart -- a 1Hz sprite cannot be driven by the renderer.

--check exits non-zero if board.html is out of date with crew.swift, so `crew
doctor` can notice the sidebar's cat moving on without the board's.
"""

import ast
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
SWIFT = pathlib.Path.home() / ".config" / "cmux" / "sidebars" / "crew.swift"
PAGE = HERE / "board.html"
PX = 3                       # crew.swift's `let px = 3.0`
POSES = ["NAP_A", "NAP_B", "WALK_A", "WALK_B", "SWAT_A", "SWAT_B"]

# catColor() in crew.swift. The body is charcoal rather than black on purpose:
# against a near-black sidebar a true-black cat is a hole in the screen and only
# its white markings read.
COLOR = {
    1: "#36363F",   # body — charcoal, not black
    2: "#F5F5F7",   # bib, paws, muzzle, tail tip
    3: "#8BE07C",   # eye, open
    4: "#F4A6B8",   # nose
    5: "#5A5A62",   # eye, closed
    6: "#22222A",   # inner ear / shading
}

BEGIN = "<!-- CAT:BEGIN generated by cat_from_swift.py -->"
END = "<!-- CAT:END -->"


def poses():
    src = SWIFT.read_text()
    out = {}
    for name in POSES:
        m = re.search(r"let %s = (\[\[.*?\]\])\n" % name, src, re.S)
        if not m:
            raise SystemExit("cat_from_swift: %s not found in %s" % (name, SWIFT))
        out[name] = ast.literal_eval(m.group(1))
    return out


def path_for(pixels, colour):
    """One path per colour: every pixel a PXxPX square."""
    d = []
    for x, y, c in pixels:
        if c != colour:
            continue
        d.append("M%d %dh%dv%dh-%dz" % (x * PX, y * PX, PX, PX, PX))
    return "".join(d)


def svg():
    ps = poses()
    # Widest pose plus the pace travel, so the cat never clips as it walks.
    span = max(x for p in ps.values() for x, _y, _c in p) + 1
    w, h = span * PX + 36, (max(y for p in ps.values() for _x, y, _c in p) + 2) * PX
    lines = [BEGIN,
             '    <svg id="cat" class="nap" viewBox="0 0 %d %d" aria-hidden="true">' % (w, h),
             '      <g class="walker"><g class="facing">']
    for name in POSES:
        cls = name.lower().replace("_", "-")
        lines.append('        <g class="pose %s">' % cls)
        for idx in sorted(COLOR):
            d = path_for(ps[name], idx)
            if d:
                lines.append('          <path fill="%s" d="%s"/>' % (COLOR[idx], d))
        lines.append("        </g>")
    lines.append("      </g></g>")
    # Three z's on staggered phases: a breathing curve alone reads as a static
    # sprite at this size, and drifting z's are unmistakable.
    for i in range(3):
        lines.append('      <text class="zz z%d" x="%d" y="%d">z</text>'
                     % (i, 44 + i * 5, 14 - i * 2))
    lines.append("    </svg>")
    lines.append("    " + END)
    return "\n".join(lines)


def main():
    want = svg()
    page = PAGE.read_text()
    i, j = page.find(BEGIN), page.find(END)
    if i < 0 or j < 0:
        raise SystemExit("cat_from_swift: markers not found in board.html")
    have = page[i:j + len(END)].rstrip()
    cur = want.strip()
    # Compare on the sprite only, ignoring the leading indent of the block.
    if "--check" in sys.argv:
        ok = re.sub(r"\s+", "", have) == re.sub(r"\s+", "", cur)
        print("cat is in sync with crew.swift" if ok else
              "cat is STALE: re-run cat_from_swift.py")
        return 0 if ok else 1
    PAGE.write_text(page[:i] + cur + page[j + len(END):])
    px = sum(len(p) for p in poses().values())
    print("wrote %d poses, %d pixels" % (len(POSES), px))
    return 0


if __name__ == "__main__":
    sys.exit(main())
